# Generated by Django 5.1.7 on 2025-03-09 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=20, unique=True)),
                ('policy_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('policy_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=10)),
                ('blockchain_transaction_hash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('blockchain_transaction_hash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('is_partnered', models.BooleanField(default=True)),
                ('accreditation_number', models.CharField(max_length=50, unique=True)),
                ('insurance_accepted', models.ManyToManyField(blank=True, to='api.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('treatment_date', models.DateField(blank=True, null=True)),
                ('doctor_report', models.FileField(blank=True, null=True, upload_to='doctor_reports/')),
                ('policyholder_comments', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_transaction_hash', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hospital')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.policy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHolderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('insurance_policies', models.ManyToManyField(blank=True, to='api.policy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('bank', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.claim')),
            ],
        ),
    ]
