# Generated by Django 5.1.7 on 2025-03-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='premium_acccount',
            new_name='premium_amount',
        ),
    ]
